### ISSUE TITLE
keystore.properties  跟encrypt.properties不见了

### ISSUE THREAD

**Issue by Jay-ch** [Bakumon/MoneyKeeper#15]
encrypt.properties keystore.properties这俩没有哦，大神发下

**Comment by Bakumon** [comment]
## 1. encrypt.properties 

encrypt.properties 是保存了加密的一些key，涉及到用户密码的保存，不能公开。
你可以自己在项目根目录下建立此文件，包含下面几个key即可
```
cipher.so {
    keys {
        aesKey {
            value = encryptProperties['KEY']
        }
        aesSalt {
            value = encryptProperties['SALT']
        }
    }
    encryptSeed = encryptProperties['CIPHER_SO_SEED']
}
```
例如：`encrypt.properties`
```
CIPHER_SO_SEED=123456789
KEY=123456789
SALT=hahaha
```
参考 [cipher.so](https://github.com/MEiDIK/Cipher.so)

## 2. keystore.properties
包含 release 版本的签名文件的密码，注释掉相关代码即可

**Comment by Jay-ch** [comment]
非常感谢
