### ISSUE TITLE
Outbound connection clarification

### ISSUE THREAD

**Issue by eternaltyro** [Bakumon/MoneyKeeper#16]
I installed the app and it's really nice. Can you clarify the outbound connection to amazonaws.com? What kind of activity is being tracked and sent?

**Comment by Bakumon** [comment]
I am very sorry that there is no timely explanation.
In fact, the act of connecting `amazonaws.com` was made by [Fabric](https://fabric.io).

>Fabric is a platform that helps your mobile team build better apps, understand your users, and grow your business.

It is used to count information such as the number of users and when the app crashes, so that I can see and solve the annoying crash in time.

**Comment by eternaltyro** [comment]
Thanks for the explanation. I really love your app!

**Comment by Bakumon** [comment]
@eternaltyro thanks
