### ISSUE TITLE
Type title

### ISSUE THREAD

**Issue by eternaltyro** [Bakumon/MoneyKeeper#18]
When I add a new type, I'm not able to type more than 5 characters.

**Comment by Bakumon** [comment]
Thanks for feedback.

This is a design that is not well thought out (only Chinese is considered). It is very unreasonable to limit the input of up to 5 characters when using English input.

Will be fixed in the next release.

Thank you!

**Comment by Bakumon** [comment]
@eternaltyro 
Because I am not good at English, the English text of this app is translated from Chinese by "Google Translate".There may be some wrong text.

I hope that you can feedback some unsuitable translations and help us make this app better.

Thank you very much🙏

**Comment by eternaltyro** [comment]
I'll definitely help with the translations. Cheers!

**Comment by eternaltyro** [comment]
With version 3.1.0 on Fdroid, this issue seems to have been solved. Thank you so much!

**Comment by Bakumon** [comment]
Yes, version 3.1.0 solves this problem
