### ISSUE TITLE
启动停顿

### ISSUE THREAD

**Issue by wenchaosong** [Bakumon/MoneyKeeper#2]
@Bakumon  启动一瞬间会有停顿

普遍来说，启动白屏一般有 2 种解决方法，一种是透明，另一种是设置图片

透明的就会造成视觉上的停顿

**Comment by Bakumon** [comment]
是的，我使用了透明的方案。

主要因为考虑到是并不需要一个启动页，并且这个启动停顿，一般来说，在冷启动时会出现，其他情况很少出现。

**Comment by wenchaosong** [comment]
@Bakumon  嗯，这个项目没有启动页，如果有启动页，设置背景图片那种你知道怎么优化吗，就是如何保证图片过大不太占内存，或者怎么用代码控制而不是 xml 控制

**Comment by Bakumon** [comment]
透明 的方案体验不太好，改成了设置背景色的方式
