### ISSUE TITLE
cipher-lib.cpp里面有一个头文件不存在？

### ISSUE THREAD

**Issue by MyBackups-Home** [Bakumon/MoneyKeeper#41]
请问extern-keys.h是什么？找不到这个头文件，报错了

**Comment by Bakumon** [comment]
https://github.com/MEiDIK/Cipher.so 
依赖的是上面这个库，你是在编译时出现问题了吗

**Comment by MyBackups-Home** [comment]
现在编译完成后没有报错，就是这个cpp文件报红缺了这个头文件

**Comment by Bakumon** [comment]
@MyBackups-Home 对加密有影响吗，有影响的话，你可以去原库提 issues

**Comment by MyBackups-Home** [comment]
@Bakumon  啊～编译！说错了，我还没编译出来，是build完之后没有报错，我等下编译看看有没问题（习惯性检查有没问题再编译了🙈
