### ISSUE TITLE
取消订阅是mDisposable管理吗？

### ISSUE THREAD

**Issue by chusong** [Bakumon/MoneyKeeper#6]
内存泄露是mDisposable管理吗？好像mDisposable.clear();并不能接触订阅，还是说你在其他地方管理订阅控制内存泄露的，最近在看rxjava生命周期，望指点

**Comment by Bakumon** [comment]
rxjava2中，
`Disposable#dispose()`:主动解除订阅
`CompositeDisposable` 中包含一个`Disposable`的集合，`CompositeDisposable#clear()`方法会自动解除所有通过`CompositeDisposable#add()`添加到这个集合中的所有`Disposable`

**Comment by chusong** [comment]
我大概瞎了，没看到你的订阅都是通过CompositeDisposable.add()添加的，谢谢解答
