### ISSUE TITLE
数据库升级

### ISSUE THREAD

**Issue by TKMapleLeaf** [Bakumon/MoneyKeeper#7]
Room表中增加字段，Room怎么升级？

**Comment by Bakumon** [comment]
@TKMapleLeaf 请参考 [Room官方文档](https://developer.android.google.cn/training/data-storage/room/migrating-db-versions)

**Comment by TKMapleLeaf** [comment]
@Dao注解，在编译的时候就报错，找不到新字段。再看看文档，是否漏了什么

**Comment by Bakumon** [comment]
代码贴出来，我帮你看看
