### ISSUE TITLE
Hi Can I use your code and modify it and publish it on Google play?

### ISSUE THREAD

**Issue by craftyendeavour** [Bakumon/MoneyKeeper#8]
Thanks for this beautiful app. I would like to modify it and publish it on google play. If you allow it. I'll be giving you the full credits for that. 
Thanks :)

**Comment by Bakumon** [comment]
I'm Sorry,  I can't allow your request.Because I also plan to publish my app to Google Play, and I have already published to [coolapk](https://www.coolapk.com/) app market. Google Play is the second choice to be released.
