### ISSUE TITLE
点击报表页面标题的时间崩溃

### ISSUE THREAD

**Issue by cherry-cheng** [Bakumon/MoneyKeeper#9]
目前学习阶段，点击报表时间标题会崩溃，解了崩溃，里面的时间拉不动？？？

**Comment by Bakumon** [comment]
这里目前的确是存在崩溃的。
项目全部代码转换为 kotlin 后，[PickerLayoutManager](https://github.com/Bakumon/MoneyKeeper/blob/master/app/src/main/java/me/bakumon/moneykeeper/view/PickerLayoutManager.kt#L82)会莫名的数组越界，修改中，如果你发现了问题所在，欢迎修改提 pull requests
